name: Python Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    # リポジトリのコードをチェックアウト
    - name: Check out code
      uses: actions/checkout@v3

    # Python をセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # 必要な依存関係をインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # flake8 を使用してコードスタイルチェック
    - name: Run flake8
      run: flake8 .

    # black を使用してコードフォーマットチェック
    - name: Run black (check only)
      run: black --check .

    # mypy を使用して型チェック
    - name: Run mypy
      run: mypy .

    # reviewdog を使用して flake8 の結果をコメントとして表示
    - name: Run flake8 with reviewdog
      run: |
        flake8 . | reviewdog -f=flake8 -name="flake8" -reporter=github-pr-review -level=error
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # reviewdog を使用して black の結果をコメントとして表示
    - name: Run black with reviewdog
      run: |
        black --check . | reviewdog -f="diff" -name="black" -reporter=github-pr-review -level=warning
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
